#!/bin/sh

set -e

lb config noauto \
	--clean \
	--ignore-system-defaults \
	--mode debian \
	--debian-installer live \
	--bootappend-live "boot=live components locales=zh_CN.UTF-8 keyboard-layouts=us timezone=Asia/Shanghai" \
	--linux-packages "linux-image linux-headers" \
	--source false \
	--distribution stable \
	--parent-distribution stable \
	--updates true \
	--backports false \
	--apt-source-archives false \
	--archive-areas "main non-free-firmware non-free contrib" \
	--parent-archive-areas "main non-free-firmware non-free contrib" \
	--mirror-bootstrap https://mirrors.aliyun.com/debian \
	--mirror-binary https://mirrors.aliyun.com/debian \
	--mirror-binary-security https://mirrors.aliyun.com/debian-security \
	--mirror-chroot https://mirrors.aliyun.com/debian \
	--mirror-chroot-security https://mirrors.aliyun.com/debian-security \
	--parent-mirror-bootstrap https://mirrors.aliyun.com/debian \
	--parent-mirror-binary https://mirrors.aliyun.com/debian \
	--parent-mirror-binary-security https://mirrors.aliyun.com/debian-security \
	--parent-mirror-chroot https://mirrors.aliyun.com/debian \
	--parent-mirror-chroot-security https://mirrors.aliyun.com/debian-security \
	--checksums sha256 \
	--chroot-filesystem squashfs \
	--firmware-chroot true \
	--memtest memtest86+ \
	--bootloaders "grub-efi"
"${@}"
