#!/bin/sh

set -e

bootloader="grub-efi"

if [ "$(dpkg --print-architecture)" = "amd64" ]; then
    bootloader="syslinux grub-efi"
fi

lb config noauto \
	--clean \
	--ignore-system-defaults \
	--mode debian \
	--bootappend-live "boot=live components locales=zh_CN.UTF-8 keyboard-layouts=us timezone=Asia/Shanghai" \
	--bootappend-live-failsafe "boot=live components memtest noapic noapm nodma nomce nosmp nosplash vga=788 locales=zh_CN.UTF-8 keyboard-layouts=us timezone=Asia/Shanghai" \
	--linux-packages "linux-image linux-headers" \
	--source false \
	--distribution trixie \
	--parent-distribution trixie \
	--updates true \
	--backports false \
	--apt-source-archives false \
	--archive-areas "main non-free-firmware non-free contrib" \
	--parent-archive-areas "main non-free-firmware non-free contrib" \
	--mirror-bootstrap https://mirrors.aliyun.com/debian \
	--mirror-binary https://mirrors.aliyun.com/debian \
	--mirror-binary-security https://mirrors.aliyun.com/debian-security \
	--mirror-chroot https://mirrors.aliyun.com/debian \
	--mirror-chroot-security https://mirrors.aliyun.com/debian-security \
	--parent-mirror-bootstrap https://mirrors.aliyun.com/debian \
	--parent-mirror-binary https://mirrors.aliyun.com/debian \
	--parent-mirror-binary-security https://mirrors.aliyun.com/debian-security \
	--parent-mirror-chroot https://mirrors.aliyun.com/debian \
	--parent-mirror-chroot-security https://mirrors.aliyun.com/debian-security \
	--checksums sha256 \
	--chroot-filesystem squashfs \
	--memtest memtest86+ \
	--bootloaders "$bootloader" \
    --iso-application "THOS" \
    --iso-preparer "" \
    --iso-publisher "" \
	--iso-volume "THOS 0.9 $(dpkg --print-architecture)"
"${@}"
